version: '3.8'
services:
  claude-relay:
    image: weishaw/claude-relay-service:latest
    container_name: claude-relay-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      # 使用本地Redis而不是容器Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      # 容器代理配置（用于访问外网API）
      - HTTP_PROXY=http://host.docker.internal:7897
      - HTTPS_PROXY=http://host.docker.internal:7897
      - NO_PROXY=localhost,127.0.0.1,host.docker.internal
      # 其他配置
      - LOG_LEVEL=${LOG_LEVEL}
      - TIMEZONE_OFFSET=${TIMEZONE_OFFSET}
      - WEB_TITLE=${WEB_TITLE}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    extra_hosts:
      # 允许容器访问宿主机服务
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# 注释掉Redis服务，因为使用本地Redis
# redis:
#   image: redis:7-alpine
#   container_name: claude-relay-redis
#   restart: unless-stopped
#   volumes:
#     - redis_data:/data

# volumes:
#   redis_data: